#!/usr/bin/env python3
"""
Dump the RemixIcon glyph-name -> codepoint map out of the bundled woff2 into
tools/icon-map.php, which tools/build-icons.php consumes.

The font itself is the only complete source of truth left in the repo: the
upstream remixicon.css was intentionally removed once the subset stylesheet
was generated, so nothing else records the codepoints.

Usage:  python tools/dump-icon-map.py
Requires: pip install fonttools brotli
"""
import os
import sys

try:
    from fontTools.ttLib import TTFont
except ImportError:
    sys.exit('fonttools is required: pip install fonttools brotli')

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, 'assets', 'fonts', 'remixicon.woff2')
OUT = os.path.join(ROOT, 'tools', 'icon-map.php')


def main():
    font = TTFont(FONT)
    cmap = font.getBestCmap()

    # Glyph names in this font are the icon names without the 'ri-' prefix
    # (e.g. 'alert-line').
    #
    # The font's `post` table is lossy for some pairs: it labels BOTH members
    # of a fill/line pair '<name>-fill', so 'close-line' and 'loader-4-line'
    # are unreachable by name alone. RemixIcon always lays a pair out at
    # consecutive codepoints, fill first and line second, so when a '-fill'
    # name repeats at code+1 the second entry is really the '-line' variant.
    # Repairing it here is what makes the map complete.
    mapping = {}
    entries = sorted(cmap.items())
    seen = {}

    for code, name in entries:
        hexcode = '%04x' % code
        if name in seen and name.endswith('-fill') and code == seen[name] + 1:
            repaired = name[: -len('-fill')] + '-line'
            mapping.setdefault(repaired, hexcode)
            continue
        seen[name] = code
        mapping.setdefault(name, hexcode)

    lines = [
        '<?php',
        '/**',
        ' * RemixIcon glyph name => codepoint, extracted from',
        ' * assets/fonts/remixicon.woff2. Generated by tools/dump-icon-map.py —',
        ' * do not edit by hand. Consumed by tools/build-icons.php.',
        ' */',
        'return [',
    ]
    for name, code in sorted(mapping.items()):
        lines.append("    '%s' => '%s'," % (name, code))
    lines.append('];')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')

    print('wrote %s (%d glyphs)' % (os.path.relpath(OUT, ROOT), len(mapping)))


if __name__ == '__main__':
    main()
